/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface ICaller {
    function noInputNoOutput(address callee_addr) external view;

    function oneInputOneOutput(address callee_addr, uint256 input) external view returns (uint256);

    function multipleInputsMultipleOutputs(address callee_addr, uint256 input1, address input2) external view returns (uint256, bool, address, bytes32);

    function mutable(address callee_addr) external returns (bool);

    function fails(address callee_addr) external view;

    function outputsResultOk(address callee_addr) external view returns (uint256, uint256);

    function outputsResultErr(address callee_addr) external view returns (uint256);

    function outputsArbresultOk(address callee_addr) external view returns (uint8[] memory);

    function outputsArbresultErr(address callee_addr) external view returns (uint8[] memory);
}
