/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface ISendEther {
    function sendViaTransfer(address to) external payable;

    function sendViaCall(address to) external payable;

    function sendViaCallGasLimit(address to, uint64 gas_amount) external payable;

    function sendViaCallWithCallData(address to, bytes calldata data) external payable;

    function sendToStylusContract(address to) external payable;
}
