/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IMapping  {
    function getMyMap(address target) external view returns (bool);

    function setMyMap(address target, bool new_value) external;

    function removeMyMap(address target) external;

    function getMyNestedMap(uint256 index, address target) external view returns (bool);

    function setMyNestedMap(uint256 index, address target, bool new_value) external;

    function removeMyNestedMap(uint256 index, address target) external;
}
