/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface ICounter  {
    function owner() external view returns (address);

    function number() external view returns (uint256);

    function lastUpdated() external view returns (uint256);

    function setNumber(uint256 new_number) external;

    function mulNumber(uint256 new_number) external;

    function addNumber(uint256 new_number) external;

    function increment() external;

    function decrement() external;

    function addFromMsgValue() external payable;

    function callExternalContract(address target, uint8[] memory data) external returns (uint8[] memory);

    function transferOwnership(address new_owner) external;
}
