/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface ITuples {
    function numbers() external returns (uint256, uint256, uint256);

    function bytesAndNumber() external returns (bytes memory, uint256);
}
