/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IStylusTestNFT  {
    function mint() external;

    function mintTo(address to) external;

    function burn(uint256 token_id) external;

    function totalSupply() external returns (uint256);

    error InvalidTokenId(uint256);

    error NotOwner(address, uint256, address);

    error NotApproved(address, address, uint256);

    error TransferToZero(uint256);

    error ReceiverRefused(address, uint256, bytes4);
}
