/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IExampleContract  {
    function execute(address target, bytes calldata data) external view returns (bytes memory);

    function simpleCall(address account, address user) external returns (string memory);

    function callWithGasValue(address account, address user) external payable returns (string memory);

    function callPure(address methods) external view;

    function callView(address methods) external view;

    function callWrite(address methods) external;

    function callPayable(address methods) external payable;

    function makeGenericCall(address account, address user) external returns (string memory);

    function executeCall(address _contract, uint8[] memory calldata) external returns (uint8[] memory);

    function executeStaticCall(address _contract, uint8[] memory calldata) external returns (uint8[] memory);

    function rawCallExample(address _contract, uint8[] memory calldata) external returns (uint8[] memory);
}
