/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface INestedStructs {
    function addUser(address _address, string calldata name) external;

    function addDogs(address user, Dog[] memory dogs) external;

    function getUser(address _address) external view returns (User);

    function getAllUsers() external view returns (User[] memory);

    error NotFound();

    error AlreadyExists();

    error InvalidParam();

    struct Dog {string name;string breed;}

    struct User {address _address;string name;Dog[] dogs;}
}
