/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IArrays  {
    function push(uint256 i) external;

    function getElement(uint256 index) external view returns (uint256);

    function getArrLength() external view returns (uint256);

    function remove(uint256 index) external;

    function getArr2Element(uint256 index) external view returns (uint256);

    function getArr2Length() external view returns (uint256);

    function setArr2Value(uint256 index, uint256 value) external;

    function pushArr3Info(uint256 value) external;

    function getArr3Length() external view returns (uint256);

    function getArr3Info(uint256 index) external view returns (address, uint256);

    function findArr3FirstExpectedValue(uint256 expected_value) external view returns (uint256);
}
