/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IPaymentTracker  {
    function getBalance(address account) external view returns (uint256);

    function getStats() external view returns (uint256, uint256, uint256);
}
