/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface ITupleWithVariableSizesElements  {
    function onlyString() external view returns (string memory);

    function onlyVec() external view returns (uint8[] memory);

    function u256AndU256() external view returns (uint256, uint256);

    function u256AndString() external view returns (uint256, string memory);

    function u256AndVec() external view returns (uint256, uint8[] memory);
}
